### ISSUE TITLE
WAS 403 response

### ISSUE THREAD

**Issue by javrav2** [packetchaos/navi#10] opened 2020-07-09 16:07 UTC
While creating a WAS scan i am getting a 403 response while using my admin account. 

You are not authorized! You need to be an admin
 <Response [403]>

**Comment by packetchaos** [comment] 2020-07-09 16:45
Tenable just switched from V1 to V2 of the WAS products...  Can you elaborate on which command you used?

Did you use the "navi was --scan myurl"?

**Comment by packetchaos** [comment] 2020-07-09 16:45
I will be removing the old V1 reference in Navi this weekend...

**Comment by javrav2** [comment] 2020-07-09 17:51
Yes i used --> navi was --scan myurl

**Comment by packetchaos** [comment] 2020-07-09 18:03
When did you receive the 403 error?  After choosing a template?  Did you get to walk through the options?

**Comment by javrav2** [comment] 2020-07-09 18:16
Yes i chose the template, selected the scanner and then selected my user which is admin. After Gave me 403 error

**Comment by packetchaos** [comment] 2020-07-09 18:26
Which template did you choose? I will test it out now.

**Comment by javrav2** [comment] 2020-07-09 18:30
i chose 2 web app scan

**Comment by javrav2** [comment] 2020-07-09 18:31
awesome, thank you! Great tool by the way!

**Comment by packetchaos** [comment] 2020-07-09 23:23
So I can't duplicate the error on the newest version 5.1.34.

Are you using it in a container?

**Comment by packetchaos** [comment] 2020-07-09 23:35
Okay...Looks like my build process is out of sync...The container was behind.  I just had the container rebuilt.  So if you are using docker, pull the newest container and try it again.

If you have confirmed you are using the latest version, I would double-check that your API keys are from and admin account and that WAS is still active in your T.io. container.

**Comment by packetchaos** [comment] 2020-07-09 23:36
Last...I will add a "navi version" command to make it easier to get said version. :)

**Comment by javrav2** [comment] 2020-07-13 19:58
Its working for me now :-)

**Comment by packetchaos** [comment] 2020-07-13 20:03
Sweet!  Sorry for the hassle. My build and package pipeline was out of sync.   I will close this ticket as complete.

Let me know if you have any improvement suggestions.

Have a great day!

**Closed as completed by packetchaos** 2020-07-13 20:03 UTC
